### ISSUE TITLE
Differences from "no-restricted-paths" plugin

### ISSUE THREAD

**Issue by Venryx** [ZWkang/eslint-plugin-deny-some-modules-full-import#1]
It would be nice if the readme had a list of features, and a comparison with the existing [no-restricted-paths plugin](https://github.com/import-js/eslint-plugin-import/blob/HEAD/docs/rules/no-restricted-paths.md).

Is the main difference that you can provide a `customRenderPackageName` function?

**Comment by ZWkang** [comment]
this package more for the library not for the file.

this package more like 

when i was used lodash commonjs version.

some case like that

```js
import { get } from 'lodash'
```

this case can not worked with tree-shrinking even when i was just use lodash/get

so 

it provide a way to detect those case and give you a way to transform the code like 

```js
import get from 'lodash/get'
```

it was more focus with library import.  more focus with actually project case

---

you can check the [examples](https://github.com/ZWkang/eslint-plugin-deny-some-modules-full-import/tree/master/examples) and see how it work.

---

Thank you for paying attention to this project, it gave me a lot of encouragement

---
@Venryx

**Comment by Venryx** [comment]
True; the "no-restricted-paths" plugin is not as good for cases like lodash, because there are so many files under lodash (eg. "lodash/get", "lodash/drop", "lodash/join", etc.) that it would be impractical to list them all in the "exclude" option that it provides.

It's good to have both available, and pick the one that fits your needs. :)

**Comment by ZWkang** [comment]
@Venryx  closed
